### ISSUE TITLE
min_ios_version_supported error on running pod install

### ISSUE THREAD

**Issue by oddlyspaced** [GoogleCloudPlatform/recaptcha-enterprise-react-native#51] opened 2024-10-22 09:54 UTC
Hi, I am facing the same issue currently.
Our react native app is of version 0.70.5.

I added the package with yarn
`yarn add @google-cloud/recaptcha-enterprise-react-native
`
and on running pod install, it shows the following error :

```

[!] Invalid `Podfile` file:
[!] Invalid `recaptcha-enterprise-react-native.podspec` file: undefined local variable or method `min_ios_version_supported' for module Pod.

```
Let me know if more details are required.

**Comment by mcorner** [comment] 2024-10-22 11:07
Duplicate of #44

**Comment by mcorner** [comment] 2024-10-22 11:08
This isn't an issue with reCAPTCHA, it is some other issue with your Podfile. 

React Native defines the min_ios_version_supported via an import to your Podfile.  See an example here: 

https://github.com/GoogleCloudPlatform/recaptcha-enterprise-react-native/blob/main/example/ios/Podfile

**Closed** 2024-12-10 14:45 UTC
